import type { NewModel, NewModelYear, NewSpecCategory } from "./schema";

/**
 * Reference seed data for the Brazilian market.
 * Values are sample/illustrative — production data is curated via admin panel
 * and synced from FIPE / FENABRAVE.
 */

type FuelType = NonNullable<NewModelYear["fuelType"]>;

const ICE_FUELS: FuelType[] = [
  "gasoline",
  "ethanol",
  "flex",
  "diesel",
  "hybrid",
  "hybrid_plug_in",
  "flex_hybrid",
];
const BATTERY_FUELS: FuelType[] = ["hybrid", "hybrid_plug_in", "flex_hybrid", "electric"];
const EV_RANGE_FUELS: FuelType[] = ["electric", "hybrid_plug_in"];
const GASOLINE_FUELS: FuelType[] = ["gasoline", "flex", "hybrid", "hybrid_plug_in", "flex_hybrid"];
const ETHANOL_FUELS: FuelType[] = ["ethanol", "flex", "flex_hybrid"];
const EV_CONSUMPTION_FUELS: FuelType[] = ["electric", "hybrid_plug_in"];

export interface SeedSpec {
  categorySlug: string;
  value: string;
  numericValue?: number;
  displayValue?: string;
}

export interface SeedModelYear {
  year: number;
  fuelType: FuelType;
  fipeCode: string;
  isZeroKm: boolean;
  priceFipe: string;
  specs: SeedSpec[];
}

export interface SeedModel {
  brandSlug: string;
  name: string;
  slug: string;
  category: NewModel["category"];
  sizeCategory?: string | null;
  modelYears: SeedModelYear[];
}

export interface SeedBrand {
  name: string;
  slug: string;
  originCountry: string;
  fipeCode?: string;
  logoUrl?: string;
}

/* ------------------------------------------------------------------ */
/* Spec categories — the 14 comparison groups                          */
/* ------------------------------------------------------------------ */

export const seedSpecCategories: NewSpecCategory[] = [
  // Price
  {
    name: "Preço FIPE 0km",
    slug: "fipe-price-0km",
    unit: "R$",
    displayOrder: 1,
    group: "price",
    higherIsBetter: false,
    isNumeric: true,
  },
  {
    name: "Depreciação 12 meses",
    slug: "depreciation-12m",
    unit: "%",
    displayOrder: 2,
    group: "price",
    higherIsBetter: false,
    isNumeric: true,
  },
  // Engine
  {
    name: "Motor",
    slug: "engine-type",
    displayOrder: 10,
    group: "engine",
    isNumeric: false,
    applicableFuelTypes: ICE_FUELS,
  },
  {
    name: "Cilindros",
    slug: "cylinders",
    unit: "cil.",
    displayOrder: 11,
    group: "engine",
    higherIsBetter: true,
    isNumeric: true,
    applicableFuelTypes: ICE_FUELS,
  },
  {
    name: "Válvulas",
    slug: "valves",
    unit: "válv.",
    displayOrder: 12,
    group: "engine",
    higherIsBetter: true,
    isNumeric: true,
    applicableFuelTypes: ICE_FUELS,
  },
  {
    name: "Cilindrada",
    slug: "displacement",
    unit: "cc",
    displayOrder: 13,
    group: "engine",
    higherIsBetter: true,
    isNumeric: true,
    applicableFuelTypes: ICE_FUELS,
  },
  {
    name: "Potência",
    slug: "power",
    unit: "cv",
    displayOrder: 14,
    group: "engine",
    higherIsBetter: true,
    isNumeric: true,
  },
  {
    name: "Torque",
    slug: "torque",
    unit: "kgf·m",
    displayOrder: 15,
    group: "engine",
    higherIsBetter: true,
    isNumeric: true,
  },
  {
    name: "Injeção",
    slug: "injection",
    displayOrder: 16,
    group: "engine",
    isNumeric: false,
    applicableFuelTypes: ICE_FUELS,
  },
  {
    name: "Ignição",
    slug: "ignition",
    displayOrder: 17,
    group: "engine",
    isNumeric: false,
    applicableFuelTypes: ICE_FUELS,
  },
  { name: "Combustível", slug: "fuel-type", displayOrder: 18, group: "engine", isNumeric: false },
  {
    name: "Velocidade máxima",
    slug: "top-speed",
    unit: "km/h",
    displayOrder: 19,
    group: "engine",
    higherIsBetter: true,
    isNumeric: true,
  },
  {
    name: "0-100 km/h",
    slug: "acceleration-0-100",
    unit: "s",
    displayOrder: 20,
    group: "engine",
    higherIsBetter: false,
    isNumeric: true,
  },
  // Transmission
  {
    name: "Câmbio",
    slug: "transmission-type",
    displayOrder: 30,
    group: "transmission",
    isNumeric: false,
  },
  {
    name: "Marchas",
    slug: "gears",
    unit: "marchas",
    displayOrder: 31,
    group: "transmission",
    higherIsBetter: true,
    isNumeric: true,
  },
  { name: "Tração", slug: "traction", displayOrder: 32, group: "transmission", isNumeric: false },
  // Weight
  {
    name: "Peso",
    slug: "weight",
    unit: "kg",
    displayOrder: 40,
    group: "weight",
    higherIsBetter: false,
    isNumeric: true,
  },
  {
    name: "Peso/potência",
    slug: "weight-to-power",
    unit: "kg/cv",
    displayOrder: 41,
    group: "weight",
    higherIsBetter: false,
    isNumeric: true,
  },
  // Steering
  { name: "Direção", slug: "steering-type", displayOrder: 50, group: "steering", isNumeric: false },
  {
    name: "Diâmetro de giro",
    slug: "turning-diameter",
    unit: "m",
    displayOrder: 51,
    group: "steering",
    higherIsBetter: false,
    isNumeric: true,
  },
  // Dimensions
  {
    name: "Comprimento",
    slug: "length",
    unit: "mm",
    displayOrder: 60,
    group: "dimensions",
    higherIsBetter: true,
    isNumeric: true,
  },
  {
    name: "Largura",
    slug: "width",
    unit: "mm",
    displayOrder: 61,
    group: "dimensions",
    higherIsBetter: true,
    isNumeric: true,
  },
  {
    name: "Altura",
    slug: "height",
    unit: "mm",
    displayOrder: 62,
    group: "dimensions",
    higherIsBetter: true,
    isNumeric: true,
  },
  {
    name: "Entre-eixos",
    slug: "wheelbase",
    unit: "mm",
    displayOrder: 63,
    group: "dimensions",
    higherIsBetter: true,
    isNumeric: true,
  },
  {
    name: "Porta-malas",
    slug: "trunk",
    unit: "L",
    displayOrder: 64,
    group: "dimensions",
    higherIsBetter: true,
    isNumeric: true,
  },
  {
    name: "Tanque",
    slug: "fuel-tank",
    unit: "L",
    displayOrder: 65,
    group: "dimensions",
    higherIsBetter: true,
    isNumeric: true,
    applicableFuelTypes: ICE_FUELS,
  },
  {
    name: "Bateria",
    slug: "battery",
    unit: "kWh",
    displayOrder: 66,
    group: "engine",
    higherIsBetter: true,
    isNumeric: true,
    applicableFuelTypes: BATTERY_FUELS,
  },
  {
    name: "Autonomia",
    slug: "range",
    unit: "km",
    displayOrder: 67,
    group: "engine",
    higherIsBetter: true,
    isNumeric: true,
    applicableFuelTypes: EV_RANGE_FUELS,
  },
  // Consumption
  {
    name: "Consumo cidade (gasolina)",
    slug: "consumption-city-gasoline",
    unit: "km/l",
    displayOrder: 70,
    group: "consumption",
    higherIsBetter: true,
    isNumeric: true,
    applicableFuelTypes: GASOLINE_FUELS,
  },
  {
    name: "Consumo estrada (gasolina)",
    slug: "consumption-highway-gasoline",
    unit: "km/l",
    displayOrder: 71,
    group: "consumption",
    higherIsBetter: true,
    isNumeric: true,
    applicableFuelTypes: GASOLINE_FUELS,
  },
  {
    name: "Consumo cidade (etanol)",
    slug: "consumption-city-ethanol",
    unit: "km/l",
    displayOrder: 72,
    group: "consumption",
    higherIsBetter: true,
    isNumeric: true,
    applicableFuelTypes: ETHANOL_FUELS,
  },
  {
    name: "Consumo estrada (etanol)",
    slug: "consumption-highway-ethanol",
    unit: "km/l",
    displayOrder: 73,
    group: "consumption",
    higherIsBetter: true,
    isNumeric: true,
    applicableFuelTypes: ETHANOL_FUELS,
  },
  {
    name: "Consumo cidade (elétrico)",
    slug: "consumption-city-electric",
    unit: "kWh/100km",
    displayOrder: 74,
    group: "consumption",
    higherIsBetter: false,
    isNumeric: true,
    applicableFuelTypes: EV_CONSUMPTION_FUELS,
  },
  {
    name: "Consumo estrada (elétrico)",
    slug: "consumption-highway-electric",
    unit: "kWh/100km",
    displayOrder: 75,
    group: "consumption",
    higherIsBetter: false,
    isNumeric: true,
    applicableFuelTypes: EV_CONSUMPTION_FUELS,
  },
  // Suspension
  {
    name: "Suspensão dianteira",
    slug: "suspension-front",
    displayOrder: 80,
    group: "suspension",
    isNumeric: false,
  },
  {
    name: "Suspensão traseira",
    slug: "suspension-rear",
    displayOrder: 81,
    group: "suspension",
    isNumeric: false,
  },
  // Brakes
  {
    name: "Freio dianteiro",
    slug: "brakes-front",
    displayOrder: 90,
    group: "brakes",
    isNumeric: false,
  },
  {
    name: "Freio traseiro",
    slug: "brakes-rear",
    displayOrder: 91,
    group: "brakes",
    isNumeric: false,
  },
  // Warranty
  {
    name: "Garantia total",
    slug: "warranty-total",
    displayOrder: 100,
    group: "warranty",
    isNumeric: false,
  },
  // Accessories
  { name: "Rodas", slug: "wheels", displayOrder: 110, group: "accessories", isNumeric: false },
  { name: "Faróis", slug: "headlights", displayOrder: 111, group: "accessories", isNumeric: false },
  {
    name: "Teto solar",
    slug: "sunroof",
    displayOrder: 112,
    group: "accessories",
    isNumeric: false,
  },
  // Comfort / Technology
  {
    name: "Ar-condicionado",
    slug: "air-conditioning",
    displayOrder: 120,
    group: "comfort_technology",
    isNumeric: false,
  },
  {
    name: "Central multimídia",
    slug: "infotainment",
    displayOrder: 121,
    group: "comfort_technology",
    isNumeric: false,
  },
  {
    name: "Conectividade",
    slug: "connectivity",
    displayOrder: 122,
    group: "comfort_technology",
    isNumeric: false,
  },
  {
    name: "Assistente de estacionamento",
    slug: "parking-assist",
    displayOrder: 123,
    group: "comfort_technology",
    isNumeric: false,
  },
  // Safety
  {
    name: "Airbags",
    slug: "airbags",
    unit: "un.",
    displayOrder: 130,
    group: "safety",
    higherIsBetter: true,
    isNumeric: true,
  },
  {
    name: "Controle de estabilidade",
    slug: "esc",
    displayOrder: 131,
    group: "safety",
    isNumeric: false,
  },
  { name: "Controle de tração", slug: "tcs", displayOrder: 132, group: "safety", isNumeric: false },
  {
    name: "Assistente de rampa",
    slug: "hill-assist",
    displayOrder: 133,
    group: "safety",
    isNumeric: false,
  },
];

/* ------------------------------------------------------------------ */
/* Brands                                                              */
/* ------------------------------------------------------------------ */

export const seedBrands: SeedBrand[] = [
  {
    name: "Fiat",
    slug: "fiat",
    originCountry: "Itália",
    fipeCode: "21",
    logoUrl: "/logos/fiat.png",
  },
  {
    name: "Volkswagen",
    slug: "volkswagen",
    originCountry: "Alemanha",
    fipeCode: "59",
    logoUrl: "/logos/volkswagen.png",
  },
  {
    name: "Chevrolet",
    slug: "chevrolet",
    originCountry: "Estados Unidos",
    fipeCode: "23",
    logoUrl: "/logos/chevrolet.png",
  },
  {
    name: "Ford",
    slug: "ford",
    originCountry: "Estados Unidos",
    fipeCode: "22",
    logoUrl: "/logos/ford.png",
  },
  {
    name: "Toyota",
    slug: "toyota",
    originCountry: "Japão",
    fipeCode: "56",
    logoUrl: "/logos/toyota.png",
  },
  {
    name: "Honda",
    slug: "honda",
    originCountry: "Japão",
    fipeCode: "25",
    logoUrl: "/logos/honda.png",
  },
  {
    name: "Hyundai",
    slug: "hyundai",
    originCountry: "Coreia do Sul",
    fipeCode: "26",
    logoUrl: "/logos/hyundai.png",
  },
  {
    name: "Renault",
    slug: "renault",
    originCountry: "França",
    fipeCode: "48",
    logoUrl: "/logos/renault.png",
  },
  {
    name: "Nissan",
    slug: "nissan",
    originCountry: "Japão",
    fipeCode: "43",
    logoUrl: "/logos/nissan.png",
  },
  {
    name: "Jeep",
    slug: "jeep",
    originCountry: "Estados Unidos",
    fipeCode: "29",
    logoUrl: "/logos/jeep.png",
  },
  {
    name: "Peugeot",
    slug: "peugeot",
    originCountry: "França",
    fipeCode: "44",
    logoUrl: "/logos/peugeot.png",
  },
  {
    name: "Citroën",
    slug: "citroen",
    originCountry: "França",
    fipeCode: "13",
    logoUrl: "/logos/citroen.png",
  },
  {
    name: "Mitsubishi",
    slug: "mitsubishi",
    originCountry: "Japão",
    fipeCode: "41",
    logoUrl: "/logos/mitsubishi.png",
  },
  {
    name: "Suzuki",
    slug: "suzuki",
    originCountry: "Japão",
    fipeCode: "55",
    logoUrl: "/logos/suzuki.png",
  },
  {
    name: "Kia",
    slug: "kia",
    originCountry: "Coreia do Sul",
    fipeCode: "31",
    logoUrl: "/logos/kia.png",
  },
  { name: "BMW", slug: "bmw", originCountry: "Alemanha", fipeCode: "7", logoUrl: "/logos/bmw.png" },
  {
    name: "Mercedes-Benz",
    slug: "mercedes-benz",
    originCountry: "Alemanha",
    fipeCode: "39",
    logoUrl: "/logos/mercedes-benz.png",
  },
  {
    name: "Audi",
    slug: "audi",
    originCountry: "Alemanha",
    fipeCode: "6",
    logoUrl: "/logos/audi.png",
  },
  {
    name: "Volvo",
    slug: "volvo",
    originCountry: "Suécia",
    fipeCode: "58",
    logoUrl: "/logos/volvo.png",
  },
  {
    name: "Land Rover",
    slug: "land-rover",
    originCountry: "Reino Unido",
    fipeCode: "33",
    logoUrl: "/logos/land-rover.png",
  },
  {
    name: "Jaguar",
    slug: "jaguar",
    originCountry: "Reino Unido",
    fipeCode: "28",
    logoUrl: "/logos/jaguar.png",
  },
  {
    name: "Porsche",
    slug: "porsche",
    originCountry: "Alemanha",
    fipeCode: "47",
    logoUrl: "/logos/porsche.png",
  },
  {
    name: "Mini",
    slug: "mini",
    originCountry: "Reino Unido",
    fipeCode: "156",
    logoUrl: "/logos/mini.png",
  },
  {
    name: "Lexus",
    slug: "lexus",
    originCountry: "Japão",
    fipeCode: "34",
    logoUrl: "/logos/lexus.png",
  },
  { name: "BYD", slug: "byd", originCountry: "China", fipeCode: "238", logoUrl: "/logos/byd.png" },
  { name: "GWM", slug: "gwm", originCountry: "China", fipeCode: "240", logoUrl: "/logos/gwm.png" },
  {
    name: "Caoa Chery",
    slug: "caoa-chery",
    originCountry: "China",
    fipeCode: "245",
    logoUrl: "/logos/caoa-chery.png",
  },
  {
    name: "Omoda",
    slug: "omoda",
    originCountry: "China",
    fipeCode: "252",
    logoUrl: "/logos/omoda.png",
  },
  {
    name: "Jaecoo",
    slug: "jaecoo",
    originCountry: "China",
    fipeCode: "251",
    logoUrl: "/logos/jaecoo.png",
  },
  {
    name: "Zeekr",
    slug: "zeekr",
    originCountry: "China",
    fipeCode: "253",
    logoUrl: "/logos/zeekr.png",
  },
  {
    name: "Leapmotor",
    slug: "leapmotor",
    originCountry: "China",
    fipeCode: "260",
    logoUrl: "/logos/leapmotor.png",
  },
  {
    name: "Neta",
    slug: "neta",
    originCountry: "China",
    fipeCode: "250",
    logoUrl: "/logos/neta.png",
  },
  {
    name: "Seres",
    slug: "seres",
    originCountry: "China",
    fipeCode: "247",
    logoUrl: "/logos/seres.png",
  },
  {
    name: "MG",
    slug: "mg",
    originCountry: "Reino Unido",
    fipeCode: "167",
    logoUrl: "/logos/mg.png",
  },
  {
    name: "Caoa Changan",
    slug: "caoa-changan",
    originCountry: "China",
    fipeCode: "265",
    logoUrl: "/logos/caoa-changan.png",
  },
  {
    name: "Denza",
    slug: "denza",
    originCountry: "China",
    fipeCode: "263",
    logoUrl: "/logos/denza.png",
  },
  {
    name: "Jetour",
    slug: "jetour",
    originCountry: "China",
    fipeCode: "264",
    logoUrl: "/logos/jetour.png",
  },
  { name: "GAC", slug: "gac", originCountry: "China", fipeCode: "254", logoUrl: "/logos/gac.png" },
  {
    name: "RAM",
    slug: "ram",
    originCountry: "Estados Unidos",
    fipeCode: "185",
    logoUrl: "/logos/ram.png",
  },
  {
    name: "Subaru",
    slug: "subaru",
    originCountry: "Japão",
    fipeCode: "54",
    logoUrl: "/logos/subaru.png",
  },
];

/* ------------------------------------------------------------------ */
/* Models                                                              */
/* ------------------------------------------------------------------ */

export const seedModels: SeedModel[] = [
  {
    brandSlug: "hyundai",
    name: "HB20",
    slug: "hb20",
    category: "hatch",
    sizeCategory: "compacto",
    modelYears: [
      {
        year: 2025,
        fuelType: "flex",
        fipeCode: "008048-1",
        isZeroKm: true,
        priceFipe: "98500",
        specs: [
          { categorySlug: "engine-type", value: "1.0 Turbo Flex" },
          { categorySlug: "cylinders", value: "3", numericValue: 3 },
          { categorySlug: "valves", value: "12", numericValue: 12 },
          { categorySlug: "displacement", value: "998 cc", numericValue: 998 },
          {
            categorySlug: "power",
            value: "120 cv",
            numericValue: 120,
            displayValue: "120 cv @ 5750 rpm",
          },
          {
            categorySlug: "torque",
            value: "17.5 kgfm",
            numericValue: 17.5,
            displayValue: "17.5 kgfm @ 1500 rpm",
          },
          { categorySlug: "injection", value: "Direta" },
          { categorySlug: "ignition", value: "Eletrônica" },
          { categorySlug: "fuel-type", value: "Flex" },
          { categorySlug: "top-speed", value: "190 km/h", numericValue: 190 },
          { categorySlug: "acceleration-0-100", value: "9.9 s", numericValue: 9.9 },
          { categorySlug: "transmission-type", value: "Automática" },
          { categorySlug: "gears", value: "6", numericValue: 6 },
          { categorySlug: "traction", value: "Dianteira" },
          { categorySlug: "weight", value: "1.090 kg", numericValue: 1090 },
          { categorySlug: "steering-type", value: "Elétrica" },
          { categorySlug: "length", value: "4.284 mm", numericValue: 4284 },
          { categorySlug: "width", value: "1.720 mm", numericValue: 1720 },
          { categorySlug: "height", value: "1.470 mm", numericValue: 1470 },
          { categorySlug: "wheelbase", value: "2.530 mm", numericValue: 2530 },
          { categorySlug: "trunk", value: "300 L", numericValue: 300 },
          { categorySlug: "fuel-tank", value: "50 L", numericValue: 50 },
          { categorySlug: "consumption-city-gasoline", value: "13.5 km/l", numericValue: 13.5 },
          { categorySlug: "consumption-highway-gasoline", value: "15.2 km/l", numericValue: 15.2 },
          { categorySlug: "consumption-city-ethanol", value: "9.5 km/l", numericValue: 9.5 },
          { categorySlug: "consumption-highway-ethanol", value: "10.8 km/l", numericValue: 10.8 },
          { categorySlug: "suspension-front", value: "McPherson" },
          { categorySlug: "suspension-rear", value: "Eixo de torção" },
          { categorySlug: "brakes-front", value: "Disco ventilado" },
          { categorySlug: "brakes-rear", value: "Tambor" },
          { categorySlug: "warranty-total", value: "5 anos" },
          { categorySlug: "wheels", value: 'Liga leve 15"' },
          { categorySlug: "headlights", value: "Projetor LED" },
          { categorySlug: "air-conditioning", value: "Automático digital" },
          { categorySlug: "infotainment", value: '8" touchscreen' },
          { categorySlug: "connectivity", value: "Apple CarPlay / Android Auto" },
          { categorySlug: "airbags", value: "6", numericValue: 6 },
          { categorySlug: "esc", value: "Sim" },
          { categorySlug: "tcs", value: "Sim" },
          { categorySlug: "hill-assist", value: "Sim" },
        ],
      },
    ],
  },
  {
    brandSlug: "chevrolet",
    name: "Onix",
    slug: "onix",
    category: "hatch",
    sizeCategory: "compacto",
    modelYears: [
      {
        year: 2025,
        fuelType: "flex",
        fipeCode: "004976-3",
        isZeroKm: true,
        priceFipe: "96200",
        specs: [
          { categorySlug: "engine-type", value: "1.0 Turbo Flex" },
          { categorySlug: "cylinders", value: "3", numericValue: 3 },
          { categorySlug: "valves", value: "12", numericValue: 12 },
          { categorySlug: "displacement", value: "999 cc", numericValue: 999 },
          {
            categorySlug: "power",
            value: "116 cv",
            numericValue: 116,
            displayValue: "116 cv @ 5500 rpm",
          },
          {
            categorySlug: "torque",
            value: "16.8 kgfm",
            numericValue: 16.8,
            displayValue: "16.8 kgfm @ 2000 rpm",
          },
          { categorySlug: "injection", value: "Direta" },
          { categorySlug: "ignition", value: "Eletrônica" },
          { categorySlug: "fuel-type", value: "Flex" },
          { categorySlug: "top-speed", value: "185 km/h", numericValue: 185 },
          { categorySlug: "acceleration-0-100", value: "10.1 s", numericValue: 10.1 },
          { categorySlug: "transmission-type", value: "Automática" },
          { categorySlug: "gears", value: "6", numericValue: 6 },
          { categorySlug: "traction", value: "Dianteira" },
          { categorySlug: "weight", value: "1.075 kg", numericValue: 1075 },
          { categorySlug: "steering-type", value: "Elétrica" },
          { categorySlug: "length", value: "4.163 mm", numericValue: 4163 },
          { categorySlug: "width", value: "1.730 mm", numericValue: 1730 },
          { categorySlug: "height", value: "1.475 mm", numericValue: 1475 },
          { categorySlug: "wheelbase", value: "2.551 mm", numericValue: 2551 },
          { categorySlug: "trunk", value: "275 L", numericValue: 275 },
          { categorySlug: "fuel-tank", value: "44 L", numericValue: 44 },
          { categorySlug: "consumption-city-gasoline", value: "13.8 km/l", numericValue: 13.8 },
          { categorySlug: "consumption-highway-gasoline", value: "16.1 km/l", numericValue: 16.1 },
          { categorySlug: "consumption-city-ethanol", value: "9.7 km/l", numericValue: 9.7 },
          { categorySlug: "consumption-highway-ethanol", value: "11.3 km/l", numericValue: 11.3 },
          { categorySlug: "suspension-front", value: "McPherson" },
          { categorySlug: "suspension-rear", value: "Eixo de torção" },
          { categorySlug: "brakes-front", value: "Disco ventilado" },
          { categorySlug: "brakes-rear", value: "Tambor" },
          { categorySlug: "warranty-total", value: "3 anos" },
          { categorySlug: "wheels", value: 'Liga leve 15"' },
          { categorySlug: "headlights", value: "Projetor LED" },
          { categorySlug: "air-conditioning", value: "Manual" },
          { categorySlug: "infotainment", value: '8" touchscreen' },
          { categorySlug: "connectivity", value: "Apple CarPlay / Android Auto" },
          { categorySlug: "airbags", value: "6", numericValue: 6 },
          { categorySlug: "esc", value: "Sim" },
          { categorySlug: "tcs", value: "Sim" },
          { categorySlug: "hill-assist", value: "Sim" },
        ],
      },
    ],
  },
  {
    brandSlug: "volkswagen",
    name: "Polo",
    slug: "polo",
    category: "hatch",
    sizeCategory: "compacto",
    modelYears: [
      {
        year: 2025,
        fuelType: "flex",
        fipeCode: "005127-3",
        isZeroKm: true,
        priceFipe: "99800",
        specs: [
          { categorySlug: "engine-type", value: "1.0 Aspirado Flex" },
          { categorySlug: "cylinders", value: "3", numericValue: 3 },
          { categorySlug: "valves", value: "12", numericValue: 12 },
          { categorySlug: "displacement", value: "999 cc", numericValue: 999 },
          {
            categorySlug: "power",
            value: "109 cv",
            numericValue: 109,
            displayValue: "109 cv @ 5500 rpm",
          },
          {
            categorySlug: "torque",
            value: "16.1 kgfm",
            numericValue: 16.1,
            displayValue: "16.1 kgfm @ 3500 rpm",
          },
          { categorySlug: "injection", value: "Multiponto" },
          { categorySlug: "ignition", value: "Eletrônica" },
          { categorySlug: "fuel-type", value: "Flex" },
          { categorySlug: "top-speed", value: "182 km/h", numericValue: 182 },
          { categorySlug: "acceleration-0-100", value: "10.5 s", numericValue: 10.5 },
          { categorySlug: "transmission-type", value: "Manual" },
          { categorySlug: "gears", value: "5", numericValue: 5 },
          { categorySlug: "traction", value: "Dianteira" },
          { categorySlug: "weight", value: "1.109 kg", numericValue: 1109 },
          { categorySlug: "steering-type", value: "Elétrica" },
          { categorySlug: "length", value: "4.074 mm", numericValue: 4074 },
          { categorySlug: "width", value: "1.751 mm", numericValue: 1751 },
          { categorySlug: "height", value: "1.474 mm", numericValue: 1474 },
          { categorySlug: "wheelbase", value: "2.566 mm", numericValue: 2566 },
          { categorySlug: "trunk", value: "300 L", numericValue: 300 },
          { categorySlug: "fuel-tank", value: "52 L", numericValue: 52 },
          { categorySlug: "consumption-city-gasoline", value: "12.1 km/l", numericValue: 12.1 },
          { categorySlug: "consumption-highway-gasoline", value: "13.9 km/l", numericValue: 13.9 },
          { categorySlug: "consumption-city-ethanol", value: "8.4 km/l", numericValue: 8.4 },
          { categorySlug: "consumption-highway-ethanol", value: "9.8 km/l", numericValue: 9.8 },
          { categorySlug: "suspension-front", value: "McPherson" },
          { categorySlug: "suspension-rear", value: "Eixo de torção" },
          { categorySlug: "brakes-front", value: "Disco ventilado" },
          { categorySlug: "brakes-rear", value: "Disco sólido" },
          { categorySlug: "warranty-total", value: "3 anos" },
          { categorySlug: "wheels", value: 'Liga leve 16"' },
          { categorySlug: "headlights", value: "Halógeno" },
          { categorySlug: "air-conditioning", value: "Manual" },
          { categorySlug: "infotainment", value: '10" touchscreen' },
          { categorySlug: "connectivity", value: "Apple CarPlay / Android Auto" },
          { categorySlug: "airbags", value: "6", numericValue: 6 },
          { categorySlug: "esc", value: "Sim" },
          { categorySlug: "tcs", value: "Sim" },
          { categorySlug: "hill-assist", value: "Sim" },
        ],
      },
    ],
  },
  {
    brandSlug: "toyota",
    name: "Corolla",
    slug: "corolla",
    category: "sedan",
    sizeCategory: "médio",
    modelYears: [
      {
        year: 2025,
        fuelType: "hybrid",
        fipeCode: "002182-2",
        isZeroKm: true,
        priceFipe: "195328",
        specs: [
          { categorySlug: "engine-type", value: "1.8 16V Híbrido" },
          { categorySlug: "cylinders", value: "4", numericValue: 4 },
          { categorySlug: "valves", value: "16", numericValue: 16 },
          { categorySlug: "displacement", value: "1.798 cc", numericValue: 1798 },
          { categorySlug: "power", value: "122 cv (combinado)", numericValue: 122 },
          { categorySlug: "torque", value: "14.5 kgfm", numericValue: 14.5 },
          { categorySlug: "injection", value: "Multiponto" },
          { categorySlug: "ignition", value: "Eletrônica" },
          { categorySlug: "fuel-type", value: "Híbrido" },
          { categorySlug: "top-speed", value: "180 km/h", numericValue: 180 },
          { categorySlug: "acceleration-0-100", value: "11.5 s", numericValue: 11.5 },
          { categorySlug: "transmission-type", value: "CVT" },
          { categorySlug: "gears", value: "10 (simuladas)", numericValue: 10 },
          { categorySlug: "traction", value: "Dianteira" },
          { categorySlug: "weight", value: "1.430 kg", numericValue: 1430 },
          { categorySlug: "steering-type", value: "Elétrica" },
          { categorySlug: "length", value: "4.630 mm", numericValue: 4630 },
          { categorySlug: "width", value: "1.780 mm", numericValue: 1780 },
          { categorySlug: "height", value: "1.435 mm", numericValue: 1435 },
          { categorySlug: "wheelbase", value: "2.700 mm", numericValue: 2700 },
          { categorySlug: "trunk", value: "470 L", numericValue: 470 },
          { categorySlug: "fuel-tank", value: "43 L", numericValue: 43 },
          { categorySlug: "consumption-city-gasoline", value: "18.4 km/l", numericValue: 18.4 },
          { categorySlug: "consumption-highway-gasoline", value: "16.2 km/l", numericValue: 16.2 },
          { categorySlug: "suspension-front", value: "McPherson" },
          { categorySlug: "suspension-rear", value: "Independente multi-link" },
          { categorySlug: "brakes-front", value: "Disco ventilado" },
          { categorySlug: "brakes-rear", value: "Disco sólido" },
          { categorySlug: "warranty-total", value: "3 anos + 5 anos (bateria híbrida)" },
          { categorySlug: "wheels", value: 'Liga leve 16"' },
          { categorySlug: "headlights", value: "LED" },
          { categorySlug: "air-conditioning", value: "Automático digital dual-zone" },
          { categorySlug: "infotainment", value: '10.5" touchscreen' },
          { categorySlug: "connectivity", value: "Apple CarPlay / Android Auto sem fio" },
          { categorySlug: "airbags", value: "7", numericValue: 7 },
          { categorySlug: "esc", value: "Sim" },
          { categorySlug: "tcs", value: "Sim" },
          { categorySlug: "hill-assist", value: "Sim" },
        ],
      },
    ],
  },
  {
    brandSlug: "fiat",
    name: "Strada",
    slug: "strada",
    category: "pickup",
    sizeCategory: "picape-compacta",
    modelYears: [
      {
        year: 2025,
        fuelType: "flex",
        fipeCode: "005827-1",
        isZeroKm: true,
        priceFipe: "128990",
        specs: [
          { categorySlug: "engine-type", value: "1.3 Firefly Turbo Flex" },
          { categorySlug: "cylinders", value: "4", numericValue: 4 },
          { categorySlug: "valves", value: "16", numericValue: 16 },
          { categorySlug: "displacement", value: "1.332 cc", numericValue: 1332 },
          { categorySlug: "power", value: "132 cv", numericValue: 132 },
          { categorySlug: "torque", value: "20.4 kgfm", numericValue: 20.4 },
          { categorySlug: "fuel-type", value: "Flex" },
          { categorySlug: "transmission-type", value: "Automática" },
          { categorySlug: "gears", value: "6", numericValue: 6 },
          { categorySlug: "traction", value: "Dianteira" },
          { categorySlug: "weight", value: "1.222 kg", numericValue: 1222 },
          { categorySlug: "trunk", value: "844 L (caçamba)", numericValue: 844 },
          { categorySlug: "fuel-tank", value: "55 L", numericValue: 55 },
          { categorySlug: "warranty-total", value: "3 anos" },
          { categorySlug: "airbags", value: "6", numericValue: 6 },
          { categorySlug: "esc", value: "Sim" },
          { categorySlug: "tcs", value: "Sim" },
        ],
      },
    ],
  },
];

export const seedVehicleCategories: {
  name: string;
  slug: string;
  icon: string | null;
  displayOrder: number;
}[] = [
  { name: "Hatch", slug: "hatch", icon: "car-front", displayOrder: 1 },
  { name: "Sedan", slug: "sedan", icon: "car-front", displayOrder: 2 },
  { name: "SUV", slug: "suv", icon: "car-front", displayOrder: 3 },
  { name: "Picape", slug: "pickup", icon: "truck", displayOrder: 4 },
  { name: "Minivan", slug: "mpv", icon: "car-front", displayOrder: 5 },
  { name: "Coupé", slug: "coupe", icon: "car-front", displayOrder: 6 },
  { name: "Conversível", slug: "convertible", icon: "car-front", displayOrder: 7 },
  { name: "Perua", slug: "wagon", icon: "car-front", displayOrder: 8 },
  { name: "Van", slug: "van", icon: "truck", displayOrder: 9 },
  { name: "Elétrico", slug: "ev", icon: "zap", displayOrder: 10 },
];

export const seedSpecGroups: { name: string; slug: string; displayOrder: number }[] = [
  { name: "Preço", slug: "price", displayOrder: 1 },
  { name: "Motor", slug: "engine", displayOrder: 2 },
  { name: "Transmissão", slug: "transmission", displayOrder: 3 },
  { name: "Peso", slug: "weight", displayOrder: 4 },
  { name: "Direção", slug: "steering", displayOrder: 5 },
  { name: "Dimensões", slug: "dimensions", displayOrder: 6 },
  { name: "Consumo", slug: "consumption", displayOrder: 7 },
  { name: "Suspensão", slug: "suspension", displayOrder: 8 },
  { name: "Freios", slug: "brakes", displayOrder: 9 },
  { name: "Garantia", slug: "warranty", displayOrder: 10 },
  { name: "Acessórios", slug: "accessories", displayOrder: 11 },
  { name: "Conforto e Tecnologia", slug: "comfort_technology", displayOrder: 12 },
  { name: "Segurança", slug: "safety", displayOrder: 13 },
  { name: "Vendas", slug: "sales", displayOrder: 14 },
];
