INSERT INTO "brands" ("name", "slug", "origin_country", "fipe_code", "logo_url")
VALUES
  ('Fiat', 'fiat', 'Itália', '21', '/logos/fiat.png'),
  ('Volkswagen', 'volkswagen', 'Alemanha', '59', '/logos/volkswagen.png'),
  ('Chevrolet', 'chevrolet', 'Estados Unidos', '23', '/logos/chevrolet.png'),
  ('Ford', 'ford', 'Estados Unidos', '22', '/logos/ford.png'),
  ('Toyota', 'toyota', 'Japão', '56', '/logos/toyota.png'),
  ('Honda', 'honda', 'Japão', '25', '/logos/honda.png'),
  ('Hyundai', 'hyundai', 'Coreia do Sul', '26', '/logos/hyundai.png'),
  ('Renault', 'renault', 'França', '48', '/logos/renault.png'),
  ('Nissan', 'nissan', 'Japão', '43', '/logos/nissan.png'),
  ('Jeep', 'jeep', 'Estados Unidos', '29', '/logos/jeep.png'),
  ('Peugeot', 'peugeot', 'França', '44', '/logos/peugeot.png'),
  ('Citroën', 'citroen', 'França', '13', '/logos/citroen.png'),
  ('Mitsubishi', 'mitsubishi', 'Japão', '41', '/logos/mitsubishi.png'),
  ('Suzuki', 'suzuki', 'Japão', '55', '/logos/suzuki.png'),
  ('Kia', 'kia', 'Coreia do Sul', '31', '/logos/kia.png'),
  ('BMW', 'bmw', 'Alemanha', '7', '/logos/bmw.png'),
  ('Mercedes-Benz', 'mercedes-benz', 'Alemanha', '39', '/logos/mercedes-benz.png'),
  ('Audi', 'audi', 'Alemanha', '6', '/logos/audi.png'),
  ('Volvo', 'volvo', 'Suécia', '58', '/logos/volvo.png'),
  ('Land Rover', 'land-rover', 'Reino Unido', '33', '/logos/land-rover.png'),
  ('Jaguar', 'jaguar', 'Reino Unido', '28', '/logos/jaguar.png'),
  ('Porsche', 'porsche', 'Alemanha', '47', '/logos/porsche.png'),
  ('Mini', 'mini', 'Reino Unido', '156', '/logos/mini.png'),
  ('Lexus', 'lexus', 'Japão', '34', '/logos/lexus.png'),
  ('BYD', 'byd', 'China', '238', '/logos/byd.png'),
  ('GWM', 'gwm', 'China', '240', '/logos/gwm.png'),
  ('Caoa Chery', 'caoa-chery', 'China', '245', '/logos/caoa-chery.png'),
  ('Omoda', 'omoda', 'China', '252', '/logos/omoda.png'),
  ('Jaecoo', 'jaecoo', 'China', '251', '/logos/jaecoo.png'),
  ('Zeekr', 'zeekr', 'China', '253', '/logos/zeekr.png'),
  ('Leapmotor', 'leapmotor', 'China', '260', '/logos/leapmotor.png'),
  ('Neta', 'neta', 'China', '250', '/logos/neta.png'),
  ('Seres', 'seres', 'China', '247', '/logos/seres.png'),
  ('MG', 'mg', 'Reino Unido', '167', '/logos/mg.png'),
  ('Caoa Changan', 'caoa-changan', 'China', '265', '/logos/caoa-changan.png'),
  ('Denza', 'denza', 'China', '263', NULL),
  ('Jetour', 'jetour', 'China', '264', '/logos/jetour.png'),
  ('GAC', 'gac', 'China', '254', '/logos/gac.png'),
  ('RAM', 'ram', 'Estados Unidos', '185', '/logos/ram.png'),
  ('Subaru', 'subaru', 'Japão', '54', '/logos/subaru.png')
ON CONFLICT ("slug") DO UPDATE
SET "name" = EXCLUDED."name",
    "origin_country" = EXCLUDED."origin_country",
    "fipe_code" = EXCLUDED."fipe_code",
    "logo_url" = EXCLUDED."logo_url";
